# Generated by Django 4.2.4 on 2023-08-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApi', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default='Some direction'),
        ),
    ]
