# Generated by Django 4.2.4 on 2023-08-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApi', '0003_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.TextField(default='Empty Image'),
        ),
    ]
