# Generated by Django 4.2.4 on 2023-08-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApi', '0004_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cellphone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastName',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Some city', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default='Some department', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='SomeG', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='Some phone', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Some username', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(
                max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Some name', max_length=200),
        ),
    ]
