# Generated by Django 4.2.4 on 2023-08-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApi', '0005_remove_user_cellphone_remove_user_lastname_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='Dome', max_length=10),
        ),
    ]
