# Generated by Django 4.2.4 on 2023-08-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApi', '0006_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='passwordDefault', max_length=200),
        ),
    ]
