# Generated by Django 4.2.4 on 2023-08-30 22:28

from django.db import migrations, models
import ecommerceApi.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApi', '0007_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=ecommerceApi.models.upload_to),
        ),
    ]
