# Generated by Django 4.2.4 on 2023-08-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApi', '0008_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='applyVariants',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
