# Generated by Django 3.2.20 on 2023-09-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApi', '0009_product_applyvariants_product_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
